# Site settings
title: Docs
email: sample@sample.com
description: >
  DOCS - POC

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://sample-docs.github.io # the base hostname & protocol for your site
git_address: https://github.com/Durairaj/sample-docs
git_edit_address: https://github.com/Durairaj/sample-docs/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/New_York
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true